org: darkobits
app: inspirat
service:
  name: inspirat
plugins:
  - serverless-api-gateway-caching
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-webpack


# ----- Custom Config Data -----------------------------------------------------

custom:
  stage: ${opt:stage, 'dev'}
  basePaths:
    dev: inspirat-dev
    prod: inspirat
  # Configuration for the serverless-dotenv plugin.
  dotenv:
    include:
      - UNSPLASH_ACCESS_KEY
      - UNSPLASH_SECRET_KEY
      - UNSPLASH_COLLECTION_ID
  # Enable the serverless-api-gateway-caching plugin.
  apiGatewayCaching:
    enabled: true
  # Configuration for serverless-domain-manager plugin.
  # TODO: Remove this in a future version.
  customDomain:
    domainName: aws.frontlawn.net
    endpointType: regional
    basePath: ${self:custom.basePaths.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: true


# ----- Serverless Compute Provider Configuration ------------------------------

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  stage: ${self:custom.stage}
  environment:
    STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::inspirat-${self:custom.stage}/*


# ----- Functions --------------------------------------------------------------

functions:
  # Fetches the Inspirat photo collection using the Unsplash API and uploads the
  # response to S3.
  sync-collection:
    handler: src/sync-collection.default
    # Execute this function every hour.
    events:
      - schedule:
          name: sync-collection-${self:custom.stage}
          description: 'Sync collection from Unsplash.'
          rate: rate(1 hour)
    environment:
      UNSPLASH_ACCESS_KEY: ${env:UNSPLASH_ACCESS_KEY}
      UNSPLASH_COLLECTION_ID: ${env:UNSPLASH_COLLECTION_ID}
    timeout: 300 # (5 minutes)
  # Returns the photo collection from S3.
  get-photos:
    handler: src/get-photos.default
    # Expose this function to the public via API Gateway.
    events:
      - http:
          method: GET
          path: photos
          cors: true
          caching:
            enabled: true


# ----- CloudFormation Resource Templates --------------------------------------

resources:
  Resources:
    # S3 Bucket
    InspiratBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: inspirat-${self:custom.stage}
